name = "ScientificTypesBase"
uuid = "30f210dd-8aff-4c5f-94ba-8e64358c1161"
authors = ["Anthony D. Blaom <anthony.blaom@gmail.com>", "Thibaut Lienart <thibaut.lienart@gmail.com>"]
version = "3.0.0"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[compat]
InteractiveUtils = "1"
julia = "1"

[extras]
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Tables"]
